version: '3.8'

services:
  ev-provider-service:
    container_name: ev-provider-service
    image: ev-provider-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8082